/*

	Joins

*/

-- Lets tale a look at how we would grab data from multiple tables
SELECT STUDENT_ID, TEST_DATE, STUDENT_SCORE, MAX_SCORE
FROM TESTS, SCORES
WHERE TEST_DATE = '2018-01-01'
AND TESTS.TEST_ID = SCORES.TEST_ID;



--
SELECT SCORES.STUDENT_ID, TESTS.TEST_DATE, SCORES.STUDENT_SCORE,
TESTS.MAX_SCORE FROM TESTS, SCORES
WHERE TESTS.TEST_ID = SCORES.TEST_ID;

-- We can join as many tables as we want
SELECT CONCAT(STUDENTS.FIRST_NAME, ' ' , STUDENTS.LAST_NAME) AS NAME,
TESTS.TEST_DATE, SCORES.STUDENT_SCORE, TESTS.MAX_SCORE
FROM TESTS, SCORES, STUDENTS
WHERE TESTS.TEST_ID = SCORES.TEST_ID
AND SCORES.STUDENT_ID = STUDENTS.STUDENT_ID
ORDER BY NAME ASC;


-- List the number of absences per student
SELECT STUDENTS.STUDENT_ID,
CONCAT(STUDENTS.FIRST_NAME, ' ' , STUDENTS.LAST_NAME) AS NAME,
COUNT(ABSENCES.ABSENCE_DATE) AS ABSENCES_TO_DATE
FROM STUDENTS, ABSENCES
WHERE STUDENTS.STUDENT_ID = ABSENCES.STUDENT_ID
GROUP BY STUDENTS.STUDENT_ID;


-- left join
